backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "configuracion"
    label: "Contenido de la Web"
    delete: false
    editor:
      preview: false
    files:
      - label: "Condiciones de Trabajo"
        name: "condiciones"
        file: "datos/condiciones.json"
        fields:
          - {label: "Precio Base Videoclip", name: "precio_video", widget: "string"}
          - {label: "Texto Rodaje", name: "texto_rodaje", widget: "text"}
          - {label: "Texto Edición", name: "texto_edicion", widget: "text"}
          - {label: "Texto Entrega", name: "texto_entrega", widget: "text"}
          - {label: "Texto Desplazamientos", name: "texto_desplazamientos", widget: "text"}
          - {label: "Texto Reservas y Pagos", name: "texto_reservas", widget: "text"}

      - label: "Portafolio de Vídeos"
        name: "videos"
        file: "datos/videos.json"
        fields:
          - label: "Lista de Trabajos"
            name: "trabajos"
            widget: "list"
            summary: '{{fields.titulo}}'
            fields:
              - {label: "Título del Proyecto", name: "titulo", widget: "string"}
              - {label: "ID de YouTube", name: "youtube_id", widget: "string"}
              - {label: "Categoría (ej: Music Video)", name: "categoria", widget: "string"}
              - {label: "Director / Créditos", name: "director", widget: "string"}
